### PR TITLE
Bump to 1.0.2

### PR DESCRIPTION
**Pull request by mheon**
Changelog contained in ffcda74d6dd30babbc9ea2939ee026c181322617

Mostly usability improvements requested by Prof. Lauer
Docs have been updated to reflect changes in user experience.

Based on my feedback PR, so contains those changes as well.

### CODE REVIEW

**Comment by dmurvihill** [comment]
Okay, I am digging into this PR now. It will take probably a day to fully review.

**Comment by mheon** [comment]
If you are having trouble reading Lauer's comments, Foxit reader on Windows views them fine. Not exactly an ideal solution, but it's workable for now.

**Comment by dmurvihill** [comment]
Okay, I've finished the first round of review; looks like I'll be able to pull this tomorrow.

**Comment by mheon** [comment]
Changes based on your comments have been made

**Comment by mheon** [comment]
Fixes for your latest comments

**Comment by dmurvihill** [comment]
I will build, read, check formatting, and merge.

**Comment by dmurvihill** [comment]
I am experiencing a build issue.

output-directory seems to be relative to the main file's path, instead of relative to the working directory the command was invoked from. It definitely didn't work that way before.

This issue _does_ follow a system update (and I run Arch), but I seem to still be on a version of Latexmk dated November 2013; the latexmk executable on my system was last modified August 13, 2014, the build date of the latest release of texlive-core. This Makefile post-dates all those changes, and I swear to God it worked for me last time I tried it.

**Comment by mheon** [comment]
Builds fine on Fedora 20 latest. Would verify on my Mac, but I have separate issues there (my Latex install is somehow missing the 12-point version of the standard font)

If you can find makefile changes that make it work for you, give me a patch and i can test

**Comment by mheon** [comment]
If you have a makefile fix, please send it. Or a patch with the changes. Or tell me what to change?

**Comment by dmurvihill** [comment]
```
diff --git a/Makefile b/Makefile
index 4c70c83..f341b07 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
LATEX=latexmk
LATEX_ROOT=doc
LATEX_SRC=$(LATEX_ROOT)/src
-LATEX_DIST=$(LATEX_ROOT)/dist
+LATEX_DIST=../dist # this has to be relative to the "src" directory
LATEX_BUILD=$(LATEX_ROOT)/build
LATEX_BUILD_ARGS=-bibtex -pdf -outdir=../dist -cd
BIBLIOGRAPHY=$(LATEX_SRC)/bibliography.bib
```

**Comment by mheon** [comment]
This breaks the build on my end.

It's placing the dist/ directory in the directory above the build root (/home/mheon/code when I build from /home/mheon/code/checksims)

**Comment by mheon** [comment]
My Latexmk:

Latexmk, John Collins, 5 December 2014. Version 4.40h

Would put money on Arch being behind Fedora on this.

**Comment by dmurvihill** [comment]
I'm on 4.39, and have been since August.

**Comment by dmurvihill** [comment]
The `mklatex` documentation specifies in the `-cd` flag description that "all the generated files (aux, log, dvi, pdf, etc) will be relative to the source file." So, it seems that my build is working as documented. The [changelog](http://users.phys.psu.edu/~collins/software/latexmk-jcc/versions.html) for yesterday's release (version 4.41) says "Fix failure when using both -cd and -output-directory", which supports the theory that you are experiencing a bug that was introduced in 4.40.

I suggest adding a version number check (using `latexmk -v` and some `awk` magic) to work around this, or stop using `-cd`. We kind of have to build on latexmk 4.40.

To tell the truth, I forgot why we are using -cd at all.

**Comment by mheon** [comment]
I just removed relative paths from the makefile, in favor of absolute paths.

See if this fixes it.

**Comment by dmurvihill** [comment]
Nope. Using your Makefile:

```mkdir -p /home/d/src/checksims/doc/dist
echo "LATEX_DIST is /home/d/src/checksims/doc/dist"
LATEX_DIST is /home/d/src/checksims/doc/dist
latexmk -bibtex -pdf -outdir=/home/d/src/checksims/doc/dist -cd /home/d/src/checksims/doc/src/main.ltx
Makefile:30: recipe for target '/home/d/src/checksims/doc/dist/main.pdf' failed```

Looks like latexmk is converting it back to a relative path. How helpful...

**Comment by dmurvihill** [comment]
Still waiting on a final fix to this Makefile.

**Comment by mheon** [comment]
I no longer have time to debug environment issues, in particular ones like this. I could maaaaybe look into a Docker based solution to run on a consistent version of latexmk everywhere, but my patience for such things is limited.
Given my now far more limited time and availability, I suggest we focus on addressing Lauer's numerous comments as opposed to this.

**Pull request merged**
